[versions]
kotlin = "1.5.31"
kotlin-coroutines = "1.5.2"
ktor = "1.6.5"
logging-kermit = "1.0.0"
logging-log4j = "2.14.1"
logging-slf4j = "1.7.32"

gradlePlugins-checkUpdates = "0.39.0"

# android-gradle = "7.0.3"
# android-compose = "1.0.4"
# android-activityCompose = "1.4.0"
# android-lifecycle = "2.4.0"
# android-core = "1.7.0"
# android-appcompat = "1.3.1"
# android-material = "1.4.0"
# jb-compose = "1.0.0-beta5"
# kodein = "7.6.0"

[libraries]
# Plugins
gradlePlugins-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
# android-gradle = { module = "com.android.tools.build:gradle", version.ref = "android-gradle" }
gradlePlugins-checkUpdates = { module = "com.github.ben-manes:gradle-versions-plugin", version.ref = "gradlePlugins-checkUpdates" }

# Kotlin
kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin-coroutines" }

# Ktor
ktor-server-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor" }

# Logging
logging-kermit = { module = "co.touchlab:kermit", version.ref = "logging-kermit" }
logging-log4j-api = { module = "org.apache.logging.log4j:log4j-api", version.ref = "logging-log4j" }
logging-log4j-core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "logging-log4j" }
logging-log4j-slf4j = { module = "org.apache.logging.log4j:log4j-slf4j-impl", version.ref = "logging-log4j" }
logging-slf4j = { module = "org.slf4j:slf4j-api", version.ref = "logging-slf4j" }

# Kodein
# kodein-core = { module = "org.kodein.di:kodein-di", version.ref = "kodein" }
# kodein-compose = { module = "org.kodein.di:kodein-di-framework-compose", version.ref = "kodein" }

# Android Compose
# android-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "android-compose" }
# android-compose-material = { module = "androidx.compose.material:material", version.ref = "android-compose" }
# android-compose-uiTooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "android-compose" }
# android-compose-uiToolingPreview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "android-compose" }
# Other Android
# android-core = { module = "androidx.core:core-ktx", version.ref = "android-core" }
# android-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "android-appcompat" }
# android-material = { module = "com.google.android.material:material", version.ref = "android-material" }
# android-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "android-activityCompose" }
# android-lifecycle = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "android-lifecycle" }
