[versions]
kotlin = "1.5.31"
# kotlin-coroutine = "1.5.0"
gradlePlugins-checkUpdates = "0.39.0"
# android-gradle = "7.0.3"
# android-compose = "1.0.4"
# android-activityCompose = "1.4.0"
# android-lifecycle = "2.4.0"
# android-core = "1.7.0"
# android-appcompat = "1.3.1"
# android-material = "1.4.0"
# jb-compose = "1.0.0-beta5"
# kodein = "7.6.0"
#
[libraries]
# Plugins
# kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
# android-gradle = { module = "com.android.tools.build:gradle", version.ref = "android-gradle" }
gradlePlugins-checkUpdates = { module = "com.github.ben-manes:gradle-versions-plugin", version.ref = "gradlePlugins-checkUpdates" }
#
# # Kotlin
# kotlin-coroutine-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin-coroutine" }
#
# # Kodein
# kodein-core = { module = "org.kodein.di:kodein-di", version.ref = "kodein" }
# kodein-compose = { module = "org.kodein.di:kodein-di-framework-compose", version.ref = "kodein" }
#
# # JB Compose
# jb-compose-gradle = { module = "org.jetbrains.compose:compose-gradle-plugin", version.ref = "jb-compose" }
#
# # Android Compose
# android-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "android-compose" }
# android-compose-material = { module = "androidx.compose.material:material", version.ref = "android-compose" }
# android-compose-uiTooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "android-compose" }
# android-compose-uiToolingPreview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "android-compose" }
# # Other Android
# android-core = { module = "androidx.core:core-ktx", version.ref = "android-core" }
# android-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "android-appcompat" }
# android-material = { module = "com.google.android.material:material", version.ref = "android-material" }
# android-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "android-activityCompose" }
# android-lifecycle = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "android-lifecycle" }
