# Default config location
# https://github.com/detekt/detekt/blob/master/detekt-core/src/main/resources/default-detekt-config.yml

complexity:
  LongParameterList:
    active: false
  LongMethod:
    active: false
  TooManyFunctions:
    active: false
naming:
  PackageNaming:
    packagePattern:  '[a-z]+(\.[a-z][A-Za-z0-9_]*)*'
