name: ci

on:
  push:
    branches:
      - master
jobs:
  ci:
    name: ci
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    steps:
      - name: Clone vs-iot repository
        uses: actions/checkout@v2
        with:
          path: vs-iot

      - name: Clone vs-core repository
        uses: actions/checkout@v2
        with:
          repository: VladislavSumin/vs-core
          path: vs-core

      - name: Setup java
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 17
          cache: gradle

      - name: Run gradle
        working-directory: ./vs-iot
        run: >-
          ./gradlew
          -PpIsGithubActions=true
          -PpIsBuildAgent=true
          --scan
          :ci

      - name: Upload test result
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: test-result
          path: "**/build/reports/tests/**"